### PR TITLE
Base package that does not depend on pyqt

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ccordoba12** [comment]
What's the plan here? What would this be good for?

**Comment by hmaarrfk** [comment]
I want to create environments with pyside2, which for now is more up to date than pyqt5 (5.12 vs 5.9) (well 5.13...)

**Comment by hmaarrfk** [comment]
i might be tempted to make a PR upstream instead if that helps you?

https://github.com/jupyter/qtconsole/issues/279

**Comment by ccordoba12** [comment]
I think qtconsole should run without problem with PySide2.

**Comment by hmaarrfk** [comment]
yeah, but for now, there is a conflict between the dependencies due to requirement to install pyqt (5.9) and pyside2, which doesn't work well prior to 5.12

**Comment by ccordoba12** [comment]
Sure, I understand that. So each package that depends on PyQt should need to create a base package too?

**Comment by hmaarrfk** [comment]
that or build variants.

build variants are rather esoteric, so base packages are easier to teach and implement.

I'm also happy to push for qtpy usage, and then centralize this as a qtpy problem.

**Comment by hmaarrfk** [comment]
but, if we do centralize at a qtpy problem, then we work to have build variants there, so it wouldn't be that much burden.

**Comment by sthiele** [comment]
I also like to get rid of the `pyqt` dependency. I'm developing an application with PySide2 that uses `qtconsole`. Currently, I have to pull `qtconsole` from PyPI because otherwise I get a segfault. What is the state of this PR? Can I be of any help?

**Comment by ccordoba12** [comment]
Closing in favor of #46.

**Pull request closed without merging**
