### PR TITLE
Pin qt5

### PR DESCRIPTION
**Pull request by ocefpaf**
Another one @ccordoba12 :wink: 

(But I believe we will need to add something extra to `yum_requirements.txt` to get  passing tests.)

### CODE REVIEW

**Comment by ccordoba12** [comment]
Yeah, xvfb I guess ;-)

**Comment by jakirkham** [comment]
Why are we pinning Qt? Can we not just drop the existing pinning?

**Comment by ocefpaf** [comment]
@ccordoba12 we already have `xorg-x11-server-Xvfb`. The last commit should fix this.

**Comment by ccordoba12** [comment]
@jakirkham is right. Isn't it easier to just drop the pinning?

**Pull request merged**
